### ISSUE TITLE
LARGE_Log_System V2 this.getWrexMods()

### ISSUE THREAD

**Issue by master3395** [TheMonDon/DBM_RawData#15]
I think you should update
this.getWrexMods()
To use the new mod.
I tried only changing that part, but it seems to not react.
this.getMods()

**Comment by TheMonDon** [comment]
I'll upload the fix shortly

**Comment by TheMonDon** [comment]
https://github.com/TheMonDon/DBM_RawData/commit/2f39fe165e20c2a90e8e63ce2022a878c3e3183c
