### ISSUE TITLE
LARGE_Log_System not enabling

### ISSUE THREAD

**Issue by master3395** [TheMonDon/DBM_RawData#17]
Hello, I tried using the toggleall command, but it seems to give me an error message every time.
I have tried the other commands, and they all work.
I can enable 1 by 1 using logtoggle

![image](https://user-images.githubusercontent.com/4199669/100550565-20f18f00-327b-11eb-87dd-c30fc793d701.png)

**Comment by TheMonDon** [comment]
Hello thank you for reporting this error, I will look into it.

**Comment by TheMonDon** [comment]
I believe this issue should be fixed now.
