### ISSUE TITLE
Having major issues

### ISSUE THREAD

**Issue by WolfoTheWolf** [TheMonDon/DBM_RawData#20]
Not sure if this is my fault I have tried to install everything it wanted but it still hasn't fixed thees errors
![image](https://user-images.githubusercontent.com/56661068/103464170-9e3b7400-4cff-11eb-9d91-845482f48f49.png)

![image](https://user-images.githubusercontent.com/56661068/103464180-af848080-4cff-11eb-874d-6d306c1896e7.png)

![image](https://user-images.githubusercontent.com/56661068/103464187-b612f800-4cff-11eb-80a4-52ef4c3bd0b7.png)

**Comment by TheMonDon** [comment]
Is this an issue with trying to install quick.db?

**Comment by master3395** [comment]
> Not sure if this is my fault I have tried to install everything it wanted but it still hasn't fixed these errors

What OS are you on?
If you are on Ubuntu or Centos you should try what is listed below.
Some of the things below are posted several times, not sure why but it worked for me :)

For Ubuntu:
```
sudo apt-get install libtool
sudo apt-get install autoconf
```

For Centos 7:
```
npm i discord.js@latest
yum install libtool
yum install autoconf
```

Then
```
npm i node-gyp --save
npm config set unsafe-perm=true
npm install -g node-gyp
```
