### ISSUE TITLE
Create category Issue

### ISSUE THREAD

**Issue by daneleo** [TheMonDon/DBM_RawData#5]
I seams to get the error "Error with Event "Create Category Channel", Action #12: DiscordAPIError: Invalid Form Body type: Value "category" is not int." when running supportsetup, any way to fix this on my side or something?

Latest DBM Mods
BDM version beta - 1.4.2

Thanks Dane

**Comment by TheMonDon** [comment]
Make sure you have the latest mods from here: http://bit.ly/beta_mods

**Comment by daneleo** [comment]
installed them now its changed to Error with Event "Create Category Channel", Action #12: DiscordAPIError: Invalid Form Body type: Value "{u'position': 4, u'type': u'category'}" is not int.

**Comment by TheMonDon** [comment]
Please let me know if you still have this issue for now im closing it
